"""
Report generation in PDF and Markdown formats
"""
import os
from typing import List, Dict, Any, Optional
from datetime import datetime
from pathlib import Path
import markdown
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Image, Table, TableStyle
from reportlab.lib import colors

from .trend_models import WeeklyTrendReport, TrendItem


class ReportGenerator:
    """Generates weekly trend reports in PDF and Markdown formats"""
    
    def __init__(self, output_dir: str = None):
        """Initialize report generator"""
        self.output_dir = Path(output_dir or os.path.join(os.getcwd(), "trend_reports"))
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_markdown_report(self, 
                                report: WeeklyTrendReport,
                                viz_paths: Dict[str, str] = None) -> str:
        """Generate a comprehensive Markdown report"""
        report_id = report.report_id
        filename = f"trend_report_{report_id}.md"
        filepath = self.output_dir / filename
        
        # Build markdown content
        content = f"""# Weekly Consumer Product Trends Report
## {report.report_id}

**Report Period:** {report.week_start.strftime('%B %d, %Y')} - {report.week_end.strftime('%B %d, %Y')}  
**Generated:** {report.generated_at.strftime('%B %d, %Y at %I:%M %p')}  
**Total Items Analyzed:** {report.total_items_analyzed}

---

## Executive Summary

{report.analysis.summary}

---

## Top 10 Trends

"""
        
        # Add top trends
        for trend in report.top_trends:
            content += f"""### #{trend.rank}: {trend.title}

**Category:** {trend.category}  
**Traction Score:** {trend.traction_score:.2f}  
**Sources:** {', '.join(trend.sources)}

{trend.description}

**Why It's Trending:** {trend.why_trending}

---

"""
        
        # Category breakdown
        content += """## Category Breakdown

"""
        if report.category_breakdown:
            content += "| Category | Count | Percentage |\n"
            content += "|----------|-------|------------|\n"
            
            total = sum(report.category_breakdown.values())
            for category, count in sorted(report.category_breakdown.items(), 
                                         key=lambda x: x[1], reverse=True):
                percentage = (count / total) * 100 if total > 0 else 0
                content += f"| {category} | {count} | {percentage:.1f}% |\n"
        
        content += "\n---\n\n"
        
        # Trend Analysis
        content += """## Trend Analysis

### Common Patterns

"""
        for pattern in report.analysis.common_patterns:
            content += f"- {pattern}\n"
        
        content += """
### Emerging Categories

"""
        for category in report.analysis.emerging_categories:
            content += f"- {category}\n"
        
        content += """
### Identified Opportunities

"""
        for opportunity in report.analysis.opportunities:
            content += f"- {opportunity}\n"
        
        content += """
### Technologies Being Adopted

"""
        for tech in report.analysis.technologies:
            content += f"- {tech}\n"
        
        # Add visualizations if provided
        if viz_paths:
            content += "\n---\n\n## Visualizations\n\n"
            for viz_name, viz_path in viz_paths.items():
                content += f"![{viz_name}]({viz_path})\n\n"
        
        # Footer
        content += f"""
---

## About This Report

This report tracks consumer product trends from multiple sources including:
- Product Hunt (daily trending products)
- TechCrunch and The Verge (tech news)
- Hacker News (community discussions)
- Reddit (r/technology, r/gadgets, r/startups)

The analysis uses AI to identify patterns, emerging categories, and opportunities in the consumer product landscape.

**Categories Tracked:** {', '.join(report.categories_tracked)}

---

*Generated by BrandManager Trend Tracker v0.1.0*
"""
        
        # Write to file
        with open(filepath, 'w') as f:
            f.write(content)
        
        return str(filepath)
    
    def generate_pdf_report(self, 
                           report: WeeklyTrendReport,
                           viz_paths: Dict[str, str] = None) -> str:
        """Generate a PDF report"""
        report_id = report.report_id
        filename = f"trend_report_{report_id}.pdf"
        filepath = self.output_dir / filename
        
        # Create PDF document
        doc = SimpleDocTemplate(
            str(filepath),
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=18
        )
        
        # Container for the 'Flowable' objects
        elements = []
        
        # Define styles
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#2E86AB'),
            spaceAfter=30,
            alignment=1  # Center
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#2E86AB'),
            spaceAfter=12
        )
        
        # Title
        elements.append(Paragraph("Weekly Consumer Product Trends Report", title_style))
        elements.append(Paragraph(f"Report: {report.report_id}", styles['Heading3']))
        elements.append(Spacer(1, 0.2 * inch))
        
        # Report info
        info_text = f"""
        <b>Report Period:</b> {report.week_start.strftime('%B %d, %Y')} - {report.week_end.strftime('%B %d, %Y')}<br/>
        <b>Generated:</b> {report.generated_at.strftime('%B %d, %Y at %I:%M %p')}<br/>
        <b>Total Items Analyzed:</b> {report.total_items_analyzed}
        """
        elements.append(Paragraph(info_text, styles['Normal']))
        elements.append(Spacer(1, 0.3 * inch))
        
        # Executive Summary
        elements.append(Paragraph("Executive Summary", heading_style))
        elements.append(Paragraph(report.analysis.summary, styles['Normal']))
        elements.append(Spacer(1, 0.3 * inch))
        
        # Top Trends
        elements.append(PageBreak())
        elements.append(Paragraph("Top 10 Trends", heading_style))
        elements.append(Spacer(1, 0.2 * inch))
        
        for trend in report.top_trends:
            trend_title = f"#{trend.rank}: {trend.title}"
            elements.append(Paragraph(trend_title, styles['Heading3']))
            
            meta_text = f"<b>Category:</b> {trend.category} | <b>Score:</b> {trend.traction_score:.2f}"
            elements.append(Paragraph(meta_text, styles['Normal']))
            elements.append(Spacer(1, 0.1 * inch))
            
            elements.append(Paragraph(trend.description, styles['Normal']))
            elements.append(Spacer(1, 0.1 * inch))
            
            why_text = f"<b>Why It's Trending:</b> {trend.why_trending}"
            elements.append(Paragraph(why_text, styles['Normal']))
            elements.append(Spacer(1, 0.2 * inch))
        
        # Category Breakdown
        elements.append(PageBreak())
        elements.append(Paragraph("Category Breakdown", heading_style))
        elements.append(Spacer(1, 0.2 * inch))
        
        if report.category_breakdown:
            # Create table data
            table_data = [['Category', 'Count', 'Percentage']]
            total = sum(report.category_breakdown.values())
            
            for category, count in sorted(report.category_breakdown.items(), 
                                         key=lambda x: x[1], reverse=True):
                percentage = (count / total) * 100 if total > 0 else 0
                table_data.append([category, str(count), f"{percentage:.1f}%"])
            
            # Create table
            table = Table(table_data)
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2E86AB')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 12),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            elements.append(table)
            elements.append(Spacer(1, 0.3 * inch))
        
        # Analysis sections
        elements.append(PageBreak())
        elements.append(Paragraph("Trend Analysis", heading_style))
        elements.append(Spacer(1, 0.2 * inch))
        
        # Common Patterns
        elements.append(Paragraph("Common Patterns", styles['Heading3']))
        for pattern in report.analysis.common_patterns:
            elements.append(Paragraph(f"• {pattern}", styles['Normal']))
        elements.append(Spacer(1, 0.2 * inch))
        
        # Emerging Categories
        elements.append(Paragraph("Emerging Categories", styles['Heading3']))
        for category in report.analysis.emerging_categories:
            elements.append(Paragraph(f"• {category}", styles['Normal']))
        elements.append(Spacer(1, 0.2 * inch))
        
        # Opportunities
        elements.append(Paragraph("Identified Opportunities", styles['Heading3']))
        for opportunity in report.analysis.opportunities:
            elements.append(Paragraph(f"• {opportunity}", styles['Normal']))
        elements.append(Spacer(1, 0.2 * inch))
        
        # Technologies
        elements.append(Paragraph("Technologies Being Adopted", styles['Heading3']))
        for tech in report.analysis.technologies:
            elements.append(Paragraph(f"• {tech}", styles['Normal']))
        
        # Add visualizations if provided
        if viz_paths:
            elements.append(PageBreak())
            elements.append(Paragraph("Visualizations", heading_style))
            elements.append(Spacer(1, 0.2 * inch))
            
            for viz_name, viz_path in viz_paths.items():
                if os.path.exists(viz_path):
                    try:
                        img = Image(viz_path, width=6*inch, height=4*inch)
                        elements.append(img)
                        elements.append(Spacer(1, 0.2 * inch))
                    except Exception as e:
                        print(f"Error adding image {viz_path}: {e}")
        
        # Build PDF
        doc.build(elements)
        
        return str(filepath)
    
    def generate_both_formats(self, 
                             report: WeeklyTrendReport,
                             viz_paths: Dict[str, str] = None) -> Dict[str, str]:
        """Generate both Markdown and PDF reports"""
        return {
            'markdown': self.generate_markdown_report(report, viz_paths),
            'pdf': self.generate_pdf_report(report, viz_paths)
        }
